### PR TITLE
Prompt tinkering

### PR DESCRIPTION
**Pull request by AndreasHuber**
I changed the prompt to
- be as close as possible to the author unit suggestion on the Miro board
- reliably output a consistent JSON format

I have tested it. It looks good to me but I can give no guarantees. If you find the JSON output format to not be consistent, we may have to make the prompt even more precise.

### CODE REVIEW

**Comment by anbestCL** [comment]
I suggest a couple of changes:
- adding the key "type" to each exercise type in order to parse it more easily in the conversion
- changing the temperature to 0.2 or 0.3 to generate different exercises for the same prompt (there is gonna be a regenerate button in the frontend)
- I would keep the exercises simple for now and generate a list of exercises if we want more than one and move subtasks to the next iteration because the conversion expects the normal exercise data model and not the exercise group data model

**Comment by AndreasHuber** [comment]
> I suggest a couple of changes:
> 
>     * adding the key "type" to each exercise type in order to parse it more easily in the conversion
> 
>     * changing the temperature to 0.2 or 0.3 to generate different exercises for the same prompt (there is gonna be a regenerate button in the frontend)
> 
>     * I would like to keep the exercises simple for now and generate a list of exercises if we want more than one and move subtasks to the next iteration because the conversion expects the normal exercise data model and not the exercise group data model. If we want to keep subtasks in the first iteration, I would want the output format to be the same for 0,1 or more than 2 subtasks. Parsing of the output becomes very tedious otherwise.

Thanks for your input. 

- I assumed the client would know what exercise type it has requested and could use that information for the conversion.
- That is a valid point that I am aware of but thought can wait for the moment. If it still leads to good output we can change the temperature, yes. Should the quality suffer from a higher temperature, then I would prefer not having a regenerate button.
- I tried to follow the requirement as I understood it from the Miro board. We can discuss simplifications. An option is also to initially limit the available options on frontend side, for example no subtasks.

**Comment by AndreasHuber** [comment]
I am not sure currently if the requested JSON output format decreases the quality of generated exercises. If it does, I would like to try first generating plain text exercises with the prompts as on the Miro board and then with a second prompt ask to convert it into the desired JSON format.

**Comment by AndreasHuber** [comment]
Merging this now for two reasons:
- It seems to not have uploaded the Docker image yet because I created the PR before bumping the version. Putting it into the merge queue should change that.
- What is currently on the main branch without these changes is not useful for anyone to work with. 

If you have feedback, we can make changes in a new branch.

**Comment by anbestCL** [comment]
I made some changes in order to simplify the conversion to editor format. Furthermore I removed the plain text response and went back to output only JSON because the parsing step failed multiple times for me and outputting only JSON performed more consistently. Specifically, it outputs a task in plain text, but fails to add the JSON part and then the service outputs an error.

**Comment by AndreasHuber** [comment]
> Specifically, it outputs a task in plain text, but fails to add the JSON part and then the service outputs an error.

Was that after increasing the temperature or already before?

I was fighting with that exact issue for some time but thought to have found a prompt that worked.

**Comment by anbestCL** [comment]
> > Specifically, it outputs a task in plain text, but fails to add the JSON part and then the service outputs an error.
> 
> Was that after increasing the temperature or already before?
> 
> I was fighting with that exact issue for some time but thought to have found a prompt that worked.

It was unfortunately even before increasing the temperature. Simple regeneration with 0.0 temperature failed for me, especially when only one subtask was supposed to be generated. That is why I removed it.

**Pull request merged**
